# Exclude a variety of commonly ignored directories.
exclude = [
    "tests/*", #Test files. Style not important. Speed/correctness matters more
]

#Critical for Github Actions where we pass a list of files
force-exclude = true

line-length = 120
indent-width = 4

# Assume Python 3.10
target-version = "py310"

fix = true


[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
ignore = [
    "D100",
    "D400",
    "D415",
    "D401",   #Docstring imperative mood
    "S311",   #Insecure random functions. eg random.choice
    "W",      # New line warnings
    "FBT",    #Boolean trap linter
    "EM",     #error message linter
    "TRY003", # no long messages in exception class
    "E501",   # Line length issue. Handled by vscode itself
    "COM812", #Skip trailing comma check. Fights with vscode editor
    "G004",   # f string for logger
    "RET502", #No implcit return None
    "UP007",  #Allow optional type annotation
    "PGH",    #When to ignore type annotations
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# # Like Black, indent with spaces, rather than tabs.
indent-style = "tab"

# Like Black, use double quotes for strings.
quote-style = "double"


# # Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# # Enable auto-formatting of code examples in docstrings. Markdown,
# # reStructuredText code/literal blocks and doctests are all supported.
# #
# # This is currently disabled by default, but it is planned for this
# # to be opt-out in the future.
docstring-code-format = true
