on:
  workflow_call:
    inputs:
      project:
        description: "Describes which project we are dealing with"
        required: true
        type: string
      changed_files:
        required: true
        type: string

jobs:
  test_project:
    name: Test project provided
    runs-on: ubuntu-latest
