[tool.poetry]
name = "visits"
version = "0.1.0"
description = ""
authors = ["Lawrence Nevvon"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
