name: Lint Python Code - special linter

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - github-actions-tutorial
  workflow_dispatch:

jobs:
  lint: # The name of the job
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.py"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      #Ruff linter for checking. Replaces manual install and run.
      - uses: astral-sh/ruff-action@v3
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          src: >-
            ${{ steps.changed-files.outputs.all_changed_files }}
