name: Run Tests

on:
  pull_request:
    branches:
      - master
  workflow_call:
  workflow_dispatch:

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Changed Python files only
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.py"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  actual_tests:
    runs-on: ubuntu-latest
    name: Run Python tests
    needs: get_changed_files
    strategy:
      matrix:
        projects: ["common", "events", "visits"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
