name: Run unit and integration tests on changed Projects

on:
  workflow_call:
    inputs:
      project:
        description: "Describes which project we are dealing with"
        required: true
        type: string
      changed_files:
        required: true
        type: string

jobs:
  decide_run_test:
    name: Decide if we run test on project ${{ inputs.project}}
    runs-on: ubuntu-latest
    steps:
      - name: Run regex to check if file match
        env:
          PROJECT: ${{ inputs.project }}
          CHANGED_FILES: ${{inputs.changed_files}}
        run: |
          for file in ${CHANGED_FILES}; do
            echo ${file}
            echo ${project}
            if [[ ${file} =~ ${project} ]]; then
              echo "${file} has matched"
            fi
          done

  test_project:
    name: Test project provided
    runs-on: ubuntu-latest
    needs: decide_run_test
    steps:
      - name: Run regex to check if file match
        run: |
          echo "Hello test project"
