name: Run unit and integration tests on changed Projects

on:
  workflow_call:
    inputs:
      project:
        description: "Describes which project we are dealing with"
        required: true
        type: string
      changed_files:
        required: true
        type: string

jobs:
  decide_run_test:
    name: Decide if we run test on project ${{ inputs.project}}
    runs-on: ubuntu-latest
    outputs:
      run_test: ${{steps.if_run_test.outputs.RUN_TEST}}
    steps:
      - name: Run regex to check if file match
        id: if_run_test
        env:
          PROJECT: ${{ inputs.project }}
          CHANGED_FILES: ${{inputs.changed_files}}
        run: |
          run_tests=false
          for file in ${CHANGED_FILES}; do
            if [[ ${file} =~ "common" || ${file} =~ ${PROJECT} ]]; then
              echo "${file} has matched"
              run_tests=true
              break
            fi
          done
          echo "RUN_TEST=${run_tests}" >> "$GITHUB_OUTPUT"

  test_project:
    name: Test project provided
    runs-on: ubuntu-latest
    needs: decide_run_test
    if: ${{ needs.decide_run_test.outputs.run_test == 'true'}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.3"
      - name: Run tests with poetry
        run: |
          cd ${{ inputs.project }}
          poetry install
          poetry run pytest
